name       : attract
version    : 2.4.1
release    : 5
source     :
    - https://github.com/mickelson/attract/archive/v2.4.1.tar.gz : 77671df48abfd29ea61092dffc14b2bd4ee3bb84faa8b04b83ff9393f91aa015
license    : GPL-3.0-or-later
component  : games.emulator
summary    : A graphical front-end for command line emulators that hides the underlying
    operating system and is intended to be controlled with a joystick or gamepad.
description: |
    Attract-Mode is a graphical frontend for command line emulators such as MAME, MESS, and Nestopia. It hides the underlying operating system and is intended to be controlled with a joystick, gamepad or spin dial, making it ideal for use in arcade cabinet setups.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libarchive)
    - pkgconfig(libavcodec)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(sfml-all)
    - pkgconfig(xinerama)
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
    install -D -m00644 util/linux/attract-mode.png $installdir/usr/share/pixmaps/attract-mode.png
    install -D -m00644 util/linux/attract-mode.desktop $installdir/usr/share/applications/attract-mode.desktop
    install -D -m00644 util/linux/attract-mode.appdata.xml $installdir/usr/share/metainfo/attract-mode.appdata.xml
