name       : attract
version    : 2.2.0
release    : 1
source     :
    - https://github.com/mickelson/attract/archive/v2.2.0.tar.gz : d350a078dec7d97498846adb56fb54210e2d4bab484a8c2cd558ce197194b07b
license    : GPL-3.0
component  : games.emulator
summary    : A graphical front-end for command line emulators that hides the underlying operating system and is intended to be controlled with a joystick or gamepad.
description: |
    Attract-Mode is a graphical frontend for command line emulators such as MAME, MESS, and Nestopia. It hides the underlying operating system and is intended to be controlled with a joystick, gamepad or spin dial, making it ideal for use in arcade cabinet setups.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libarchive)
    - pkgconfig(libavcodec)
    - pkgconfig(openal)
    - pkgconfig(sfml-all)
    - pkgconfig(xinerama)
    - libjpeg-turbo-devel
build      : |
    %make prefix=/usr
install    : |
    %make_install prefix=/usr
